# automatically generated by the FlatBuffers compiler, do not modify

# namespace: 

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class Predict(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = Predict()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsPredict(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # Predict
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # Predict
    def Predict(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

def PredictStart(builder): builder.StartObject(1)
def Start(builder):
    return PredictStart(builder)
def PredictAddPredict(builder, predict): builder.PrependInt32Slot(0, predict, 0)
def AddPredict(builder, predict):
    return PredictAddPredict(builder, predict)
def PredictEnd(builder): return builder.EndObject()
def End(builder):
    return PredictEnd(builder)